### ISSUE TITLE
OpenGL video capture

### ISSUE THREAD

**Issue by Oliver1123** [INDExOS/media-for-mobile#22]
Hi, I'm trying to implement video capturing from GLSurfaceView and sometimes catch exception
```
java.lang.Exception: Cannot stop capture thread
    at org.m4m.domain.CapturePipeline.stop(CapturePipeline.java:235)
    at org.m4m.GLCapture.stop(GLCapture.java:73)
    at ___.VideoCapture.stop(VideoCapture.java:95)
    ...
```
when recording is finished. Can you give some advise with this issue?

**Comment by polaris0227** [comment]
Hi, I've got same issue when finishing record.
Sample app also has this issue.
Sometimes it works good, but sometimes app says "Capturing failed. Cannot stop capture thread." message and after that recording doesn't work even restart app.
Hope someone help me to resolve this problem.
Regards.

**Comment by deshan** [comment]
Me too have the same issue

**Comment by danzeeeman** [comment]
I'm seeing this bug today
