### ISSUE TITLE
BufferOverflowException

### ISSUE THREAD

**Issue by AdelchiF** [INDExOS/media-for-mobile#27]
On some videos I get this error:

W/System.err: java.nio.BufferOverflowException
at java.nio.ByteBuffer.put(ByteBuffer.java:787)
at org.m4m.domain.Frame.copyDataFrom(Frame.java:104)
at org.m4m.domain.pipeline.CopyDataCommandHandler.handle(CopyDataCommandHandler.java:45)
at org.m4m.domain.CommandProcessor.process(CommandProcessor.java:121)
at org.m4m.domain.CommandProcessor.process(CommandProcessor.java:93)
at org.m4m.domain.CommandProcessor.processCommandPairs(CommandProcessor.java:85)
at org.m4m.domain.CommandProcessor.process(CommandProcessor.java:57)
at org.m4m.MediaComposer$1.run(MediaComposer.java:375)
at java.lang.Thread.run(Thread.java:818)

did anyone got this error? any solution?
To me it happened selecting some small videos and transcoding.

**Comment by AdelchiF** [comment]
Ok I found what is causing the error, it happens when you try to compress a video with a mono channel audio, the only workaround found so far is to exlcude the audio from those videos
