### ISSUE TITLE
Library dependency not found (libippresample.so)

### ISSUE THREAD

**Issue by timsk159** [INDExOS/media-for-mobile#48]
Hi,

When trying to build and run the SubstituteAudioEffect sample, we receive the following error:

`at org.m4m.android.ResamplerAndroid.loadLibrary(ResamplerAndroid.java:47) at org.m4m.android.ResamplerAndroid.setup(ResamplerAndroid.java:53) at org.m4m.domain.Resampler.<init>(Resampler.java:38) at org.m4m.android.ResamplerAndroid.<init>(ResamplerAndroid.java:38) at org.m4m.effects.DifferentRateAudioReader.<init>(DifferentRateAudioReader.java:46) at org.m4m.effects.AudioReader.start(AudioReader.java:93) at org.m4m.effects.SubstituteAudioEffect.setFileUri(SubstituteAudioEffect.java:59)`

We can see in ResamplerAndroid.java that it references:

`final private String resamplerLibName = "ippresample"; // libippresample.so`

This library does not appear to be in the project anywhere, and attempts to search online have not yielded anything (we also tried downloading various packages from the intel website, but could not find it anywhere).

We found a reference in a tutorial [here](https://software.intel.com/en-us/articles/intel-inde-media-pack-for-android-tutorials-building-samples)

As you can see, others seem to be having the same issue (in the comments).

**Comment by wesleysui** [comment]
@timsk159 did you find this lib file libippresample.so ?
