### ISSUE TITLE
Could not determine artifacts error

### ISSUE THREAD

**Issue by kwony** [INDExOS/media-for-mobile#98]
Hello,

Today I tried to sync your library source via gradle and failed. It showed this error.

```
Could not determine artifacts for com.github.indexOS.media-for-mobile:android:master-SNAPSHOT:43a9026f09-1: Skipped due to earlier error
```

I am using gradle version 4.10.1. I didn't watch this error yesterday. Is there something wrong with jitpack server?

+ I checked it more deeply and found that it is causing socket timeout error

```
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
```

**Comment by kwony** [comment]
I could fix this error with an workaround patch by extending socket timeout.

```
org.gradle.jvmargs= -Dorg.gradle.internal.http.connectionTimeout=120000 -Dorg.gradle.internal.http.socketTimeout=120000
```
